In [152]:
'''
高斯消元法求解线性方程组
'''
class Hw2():
    def __init__(self):
        self.queue = 0
        self.res = []
    def gauss_elimination(self,target_mat):
        while self.queue < len(target_mat)-1:
            for i in range(self.queue+1,len(target_mat)):
                if target_mat[i,self.queue] == 0: #跳过开头已为0的行
                    continue
                tmp = target_mat[i,self.queue]/target_mat[self.queue,self.queue]
                target_mat[i] = target_mat[i] - target_mat[self.queue]*tmp
            self.queue+=1
        print("梯形矩阵为")
        print(target_mat) #输出梯形化矩阵
        res = self.solve(target_mat) #第二步，求解此方程组
        return res
        
    #求解方程组：
    def solve(self,target_mat):
        for j in range(len(target_mat)-1,-1,-1):
            if self.res:
                sub_sum = 0
                for k in range(len(self.res)):
                    sub_sum += self.res[k]*target_mat[j,self.queue+len(self.res)-k]
                self.res.append((target_mat[j,-1]-sub_sum)/target_mat[j,self.queue])
                self.queue-=1
            else:
                self.res.append(target_mat[j,-1]/target_mat[j,self.queue])
                self.queue-=1
        return self.res          

In [154]:
import numpy as np
mat1 = np.mat("1 1 1;0 4 -1;2 -2 1")
mat2 = np.mat("6;5;1")
target_mat = np.hstack((mat1,mat2))
test = Hw2()
print("增广矩阵为：")
print(target_mat)
res = test.gauss_elimination(target_mat)   
print("Xn,Xn-1…X2,X1的结果依次为：")
print(res)

增广矩阵为：
[[ 1  1  1  6]
 [ 0  4 -1  5]
 [ 2 -2  1  1]]
梯形矩阵为
[[ 1  1  1  6]
 [ 0  4 -1  5]
 [ 0  0 -2 -6]]
Xn,Xn-1…X2,X1的结果依次为：
[3.0, 2.0, 1.0]


In [63]:
a = np.mat("1,-1,1;2,1,0;2,1,-1")
b = np.array([4,3,-1])
x = np.linalg.solve(a,b)
print(x)

[1. 1. 4.]
